export const data = {
  results: [
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [18, 10402],
      id: 426150,
      original_language: 'pt',
      original_name: 'Quero Dizer-te Adeus',
      overview: 'The life and times of Orlando Silva, the famed singer from the golden age of Brazilian radio.',
      popularity: 0.076,
      poster_path: '/tRR0dqiWOnpyPBeHVBvKefvK0Oz.jpg',
      release_date: '2015-11-18',
      name: 'Quero Dizer-te Adeus',
      video: false,
      vote_average: 0,
      vote_count: 0,
      media_id: '582b39959251417b2604707c',
      media_type: 'movie'
    },
    {
      adult: false,
      backdrop_path: '/maeb2knAWzgf3bZVF0AED7Efhen.jpg',
      genre_ids: [18],
      id: 228187,
      origin_country: ['BR'],
      original_language: 'pt',
      original_name: 'Malhação: Eu Só Quero Amar',
      overview: '',
      popularity: 0.749,
      poster_path: '/mGrPEvaNXDDEq6wnnsL5flMwnPI.jpg',
      first_air_date: '2016-04-02',
      name: 'Malhação: Eu Só Quero Amar',
      vote_average: 2,
      vote_count: 1,
      media_id: '64809120e375c000ff4692ac',
      media_type: 'tv'
    },
    {
      adult: false,
      gender: 2,
      id: 28456,
      known_for_department: 'Acting',
      name: 'Alain Quercy',
      original_name: 'Alain Quercy',
      popularity: 0.97,
      profile_path: null,
      media_id: '4bc89ad8017a3c122d02176d',
      media_type: 'person',
      known_for: [
        {
          backdrop_path: '/l6UdpKKBTsBJe2Tvue4kCV7xJ9p.jpg',
          id: 122334,
          name: 'The Aristocrats',
          original_name: 'Les Aristocrates',
          overview:
            "A novel by Michel De Saint Pierre was the source for Les Aristocrates. Pierre Fresnay stars an aging Marquis, who tries his best to uphold the traditions of nobility in an ever-changing world. The Marquis' children prefer the trappings of modern society and pop culture and regard their father as a relic. This cultural clash nearly results in tragedy when two of the Marquis' offspring substitute recklessness for common sense.",
          poster_path: '/u2pkZqIUajy8CWQkrZ2rtJngppK.jpg',
          media_type: 'movie',
          media_id: '5013b90319c2955653002165',
          adult: false,
          original_language: 'fr',
          genre_ids: [18],
          popularity: 0.579,
          release_date: '1955-10-12',
          video: false,
          vote_average: 6.3,
          vote_count: 8
        },
        {
          backdrop_path: '/5AgxkrTcjgUlz9WUWGsWWyK2swY.jpg',
          id: 4195,
          name: 'Bluebeard',
          original_name: 'Landru',
          overview:
            'Paris, France, during the First World War. While thousands of soldiers die every day on the battlefields, Henri Landru, a seemingly respectable furniture dealer, married and father of four children, relentlessly feeds his own sinister factory of death.',
          poster_path: '/dnBReq5q1KlsEMqZEHn2NRs1dtl.jpg',
          media_type: 'movie',
          media_id: '4bc89d86017a3c122d0294f9',
          adult: false,
          original_language: 'fr',
          genre_ids: [18, 80, 36],
          popularity: 3.116,
          release_date: '1963-01-25',
          video: false,
          vote_average: 6.342,
          vote_count: 57
        },
        {
          backdrop_path: '/tsP5CavAJrl7oi5GNRKsbrO0kQM.jpg',
          id: 444136,
          name: 'The Last Days of Pompeii',
          original_name: 'Les Derniers Jours de Pompéi',
          overview:
            "In Pompeii in the year 79, Lycias and Helen fall in love. Helen's guardian, the high priest of Isis, wants to separate them. To do so, he tries to make Lycias drink a love potion, but a young slave threatens to reveal everything. The high priest, unable to silence her, kills her and arranges to have Lycias accused...",
          poster_path: '/52gePfagpP38zZpz6kqJYq4sAV5.jpg',
          media_type: 'movie',
          media_id: '58b478d6c3a368527d01879c',
          adult: false,
          original_language: 'fr',
          genre_ids: [36, 18],
          popularity: 0.44,
          release_date: '1950-03-02',
          video: false,
          vote_average: 5,
          vote_count: 5
        }
      ]
    },
    '<span data-media-type="/person" data-search-name="Alain Quercy">Alain Quercy</span>',
    '<span data-media-type="/person" data-search-name="Alexander Query">Alexander Query</span>',
    '<span data-media-type="/person" data-search-name="Quero Armance">Quero Armance</span>',
    '<span data-media-type="/person" data-search-name="Alejandra Quero">Alejandra Quero</span>',
    '<span data-media-type="/person" data-search-name="Arnold Quero">Arnold Quero</span>',
    '<span data-media-type="/person" data-search-name="Andres Quero Marin">Andres Quero Marin</span>',
    '<span data-media-type="/person" data-search-name="Ana Quer">Ana Quer</span>',
    '<span data-media-type="/person" data-search-name="MIlton Quero Arévalo">MIlton Quero Arévalo</span>',
    '<span data-media-type="/person" data-search-name="Alexis Valdes Quer">Alexis Valdes Quer</span>',
    '<span data-media-type="/person" data-search-name="Florencia Duery Alfsen">Florencia Duery Alfsen</span>'
  ]
}
